-- Foundational schema baseline (Slice 1 branch-validation follow-up), part 1 of 5.
-- See supabase/README.md for the full explanation of why this exists.
-- Reconstructed via read-only introspection (Supabase list_tables +
-- information_schema/pg_catalog queries), NOT a pg_dump/db push output.

create extension if not exists "uuid-ossp" with schema extensions;
create extension if not exists "pg_trgm" with schema public;

-- ── Enum types ──────────────────────────────────────────────────────────
do $$ begin
  create type org_role as enum ('admin', 'coach', 'viewer');
exception when duplicate_object then null; end $$;
do $$ begin
  create type pitch_result as enum ('ball', 'called_strike', 'swinging_strike', 'foul', 'foul_tip', 'hit_by_pitch', 'in_play', 'intentional_ball', 'pitchout');
exception when duplicate_object then null; end $$;
do $$ begin
  create type plan_tier as enum ('free', 'coach', 'organization');
exception when duplicate_object then null; end $$;
do $$ begin
  create type report_format as enum ('docx', 'pdf');
exception when duplicate_object then null; end $$;
do $$ begin
  create type report_status as enum ('pending', 'generating', 'ready', 'failed');
exception when duplicate_object then null; end $$;
do $$ begin
  create type scrape_source as enum ('gamechanger', 'perfect_game', 'manual');
exception when duplicate_object then null; end $$;
do $$ begin
  create type scrape_status as enum ('pending', 'running', 'done', 'failed');
exception when duplicate_object then null; end $$;

-- ── Sequences (verified nextval() defaults, not identity columns) ───────
create sequence if not exists public.batting_lines_id_seq;
create sequence if not exists public.pitcher_advanced_stats_id_seq;
create sequence if not exists public.pitching_lines_id_seq;
create sequence if not exists public.play_events_id_seq;
create sequence if not exists public.player_advanced_stats_id_seq;
create sequence if not exists public.scouting_reports_id_seq;

-- ── Tables ──────────────────────────────────────────────────────────────
create table if not exists public."at_bats" (
  "id" uuid NOT NULL DEFAULT extensions.uuid_generate_v4(),
  "org_id" uuid NOT NULL,
  "game_id" uuid NOT NULL,
  "batter_id" uuid,
  "pitcher_id" uuid,
  "inning" integer,
  "inning_half" text CHECK (inning_half = ANY (ARRAY['top'::text, 'bottom'::text])),
  "outcome" text,
  "rbi" integer NOT NULL DEFAULT 0,
  "runs_scored" integer NOT NULL DEFAULT 0,
  "runners_on_base" integer NOT NULL DEFAULT 0,
  "outs_at_start" integer,
  "hit_x" numeric,
  "hit_y" numeric,
  "exit_velocity" numeric,
  "hit_distance" integer,
  "sequence" integer,
  "gc_ab_id" text,
  "created_at" timestamptz NOT NULL DEFAULT now(),
  primary key ("id")
);

create table if not exists public."batting_lines" (
  "id" bigint NOT NULL DEFAULT nextval('batting_lines_id_seq'::regclass),
  "game_id" uuid NOT NULL,
  "team_id" uuid NOT NULL,
  "player_name" text NOT NULL,
  "batting_order" integer,
  "is_our_team" boolean NOT NULL DEFAULT false,
  "team_side" text,
  "team_name_raw" text,
  "position" text,
  "ab" integer NOT NULL DEFAULT 0,
  "r" integer NOT NULL DEFAULT 0,
  "h" integer NOT NULL DEFAULT 0,
  "rbi" integer NOT NULL DEFAULT 0,
  "bb" integer NOT NULL DEFAULT 0,
  "so" integer NOT NULL DEFAULT 0,
  "avg" numeric,
  "obp" numeric,
  "slg" numeric,
  "doubles" integer NOT NULL DEFAULT 0,
  "triples" integer NOT NULL DEFAULT 0,
  "hr" integer NOT NULL DEFAULT 0,
  "sb" integer NOT NULL DEFAULT 0,
  "hbp" integer NOT NULL DEFAULT 0,
  "sac" integer NOT NULL DEFAULT 0,
  "lob" integer NOT NULL DEFAULT 0,
  "raw_json" text,
  "created_at" timestamptz NOT NULL DEFAULT now(),
  "org_id" uuid,
  primary key ("id")
);

create table if not exists public."derived_team_verified_totals" (
  "team_id" uuid NOT NULL,
  "run_id" uuid,
  "updated_at" timestamptz NOT NULL DEFAULT now(),
  "games" integer NOT NULL DEFAULT 0,
  "box_score_games" integer NOT NULL DEFAULT 0,
  "play_by_play_games" integer NOT NULL DEFAULT 0,
  "validated_games" integer NOT NULL DEFAULT 0,
  "mismatch_games" integer NOT NULL DEFAULT 0,
  "batting_official" jsonb NOT NULL DEFAULT '{}'::jsonb,
  "pitching_official" jsonb NOT NULL DEFAULT '{}'::jsonb,
  "batting_reconstructed" jsonb NOT NULL DEFAULT '{}'::jsonb,
  "pitching_reconstructed" jsonb NOT NULL DEFAULT '{}'::jsonb,
  "tendencies" jsonb NOT NULL DEFAULT '{}'::jsonb,
  "warnings" jsonb NOT NULL DEFAULT '[]'::jsonb,
  "confidence" text NOT NULL DEFAULT 'low'::text CHECK (confidence = ANY (ARRAY['low'::text, 'medium'::text, 'high'::text])),
  primary key ("team_id")
);

create table if not exists public."game_stat_validation_results" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "run_id" uuid NOT NULL,
  "team_id" uuid NOT NULL,
  "game_id" uuid,
  "game_date" date,
  "opponent_name" text,
  "created_at" timestamptz NOT NULL DEFAULT now(),
  "has_box_score" boolean NOT NULL DEFAULT false,
  "has_play_by_play" boolean NOT NULL DEFAULT false,
  "scouted_side" text,
  "opponent_side" text,
  "box_scouted_batting" jsonb NOT NULL DEFAULT '{}'::jsonb,
  "reconstructed_scouted_batting" jsonb NOT NULL DEFAULT '{}'::jsonb,
  "box_scouted_pitching" jsonb NOT NULL DEFAULT '{}'::jsonb,
  "reconstructed_scouted_pitching_defense" jsonb NOT NULL DEFAULT '{}'::jsonb,
  "deltas" jsonb NOT NULL DEFAULT '{}'::jsonb,
  "batting_matches_box" boolean NOT NULL DEFAULT false,
  "quality" jsonb NOT NULL DEFAULT '{}'::jsonb,
  primary key ("id")
);

create table if not exists public."games" (
  "id" uuid NOT NULL DEFAULT extensions.uuid_generate_v4(),
  "org_id" uuid NOT NULL,
  "our_team_id" uuid NOT NULL,
  "opponent_id" uuid NOT NULL,
  "game_date" date,
  "location" text,
  "tournament_name" text,
  "our_score" integer,
  "opponent_score" integer,
  "innings_played" integer DEFAULT 7,
  "gc_game_id" text,
  "source" scrape_source NOT NULL DEFAULT 'gamechanger'::scrape_source,
  "created_at" timestamptz NOT NULL DEFAULT now(),
  "updated_at" timestamptz NOT NULL DEFAULT now(),
  "game_time" text,
  "game_datetime_raw" text,
  "json_file" text,
  "screenshot_file" text,
  "captured_at" timestamptz,
  "opponent_name" text,
  "result" text,
  "season_type" text,
  "gc_game_url" text,
  "score_us" integer,
  "score_them" integer,
  "team_id" uuid,
  primary key ("id")
);

create table if not exists public."org_members" (
  "id" uuid NOT NULL DEFAULT extensions.uuid_generate_v4(),
  "org_id" uuid NOT NULL,
  "user_id" uuid NOT NULL,
  "role" org_role NOT NULL DEFAULT 'coach'::org_role,
  "invited_by" uuid,
  "accepted_at" timestamptz,
  "created_at" timestamptz NOT NULL DEFAULT now(),
  "updated_at" timestamptz NOT NULL DEFAULT now(),
  primary key ("id")
);

create table if not exists public."organizations" (
  "id" uuid NOT NULL DEFAULT extensions.uuid_generate_v4(),
  "name" text NOT NULL,
  "slug" text NOT NULL,
  "plan" plan_tier NOT NULL DEFAULT 'free'::plan_tier,
  "stripe_customer_id" text,
  "stripe_subscription_id" text,
  "plan_expires_at" timestamptz,
  "max_opponent_teams" integer NOT NULL DEFAULT 2,
  "max_reports_per_month" integer NOT NULL DEFAULT 1,
  "max_users" integer NOT NULL DEFAULT 1,
  "contact_email" text,
  "logo_url" text,
  "created_at" timestamptz NOT NULL DEFAULT now(),
  "updated_at" timestamptz NOT NULL DEFAULT now(),
  "subscription_status" text,
  "max_self_scout_reports_per_month" integer NOT NULL DEFAULT 1,
  "max_matchup_reports_per_month" integer NOT NULL DEFAULT 1,
  "status" text NOT NULL DEFAULT 'active'::text CHECK (status = ANY (ARRAY['active'::text, 'suspended'::text, 'cancelled'::text])),
  primary key ("id")
);

create table if not exists public."pitcher_advanced_stats" (
  "id" bigint NOT NULL DEFAULT nextval('pitcher_advanced_stats_id_seq'::regclass),
  "team_id" uuid NOT NULL,
  "player_name" text NOT NULL,
  "is_our_team" boolean NOT NULL DEFAULT false,
  "generated_at" timestamptz NOT NULL DEFAULT now(),
  "games" integer,
  "total_pitches" integer,
  "strikes" integer,
  "s_pct" numeric,
  "gb" integer,
  "fb" integer,
  "ld" integer,
  "gb_pct" numeric,
  "fb_pct" numeric,
  "ld_pct" numeric,
  "go_ao" numeric,
  "so_per7" numeric,
  "bb_per7" numeric,
  "k_pct_bf" numeric,
  "bb_pct_bf" numeric,
  "p_per_ip" numeric,
  "wp" integer,
  "bk" integer,
  "pik" integer,
  "org_id" uuid,
  "errors" integer DEFAULT 0,
  primary key ("id")
);

create table if not exists public."pitches" (
  "id" uuid NOT NULL DEFAULT extensions.uuid_generate_v4(),
  "org_id" uuid NOT NULL,
  "at_bat_id" uuid NOT NULL,
  "game_id" uuid NOT NULL,
  "pitcher_id" uuid,
  "pitch_number" integer NOT NULL,
  "result" pitch_result,
  "pitch_type" text,
  "velocity" numeric,
  "strike_zone_x" numeric,
  "strike_zone_y" numeric,
  "balls_before" integer,
  "strikes_before" integer,
  "pg_pitch_id" text,
  "created_at" timestamptz NOT NULL DEFAULT now(),
  primary key ("id")
);

create table if not exists public."pitching_lines" (
  "id" bigint NOT NULL DEFAULT nextval('pitching_lines_id_seq'::regclass),
  "game_id" uuid NOT NULL,
  "team_id" uuid NOT NULL,
  "player_name" text NOT NULL,
  "is_our_team" boolean NOT NULL DEFAULT false,
  "team_side" text,
  "team_name_raw" text,
  "ip" text,
  "ip_decimal" numeric,
  "bf" integer NOT NULL DEFAULT 0,
  "pc" integer NOT NULL DEFAULT 0,
  "strikes" integer NOT NULL DEFAULT 0,
  "h_allowed" integer NOT NULL DEFAULT 0,
  "r_allowed" integer NOT NULL DEFAULT 0,
  "er" integer NOT NULL DEFAULT 0,
  "bb" integer NOT NULL DEFAULT 0,
  "so" integer NOT NULL DEFAULT 0,
  "hr_allowed" integer NOT NULL DEFAULT 0,
  "era" numeric,
  "whip" numeric,
  "raw_json" text,
  "created_at" timestamptz NOT NULL DEFAULT now(),
  "org_id" uuid,
  primary key ("id")
);

create table if not exists public."play_events" (
  "id" bigint NOT NULL DEFAULT nextval('play_events_id_seq'::regclass),
  "game_id" uuid NOT NULL,
  "team_id" uuid NOT NULL,
  "sequence_num" integer,
  "inning" text,
  "inning_num" integer,
  "inning_half" text,
  "event_type" text,
  "batter_name" text,
  "pitcher_name" text,
  "description" text,
  "runners_on" text,
  "outs_before" integer,
  "result_rbi" integer NOT NULL DEFAULT 0,
  "is_scoring_play" boolean NOT NULL DEFAULT false,
  "created_at" timestamptz NOT NULL DEFAULT now(),
  "org_id" uuid,
  primary key ("id")
);

create table if not exists public."player_advanced_stats" (
  "id" bigint NOT NULL DEFAULT nextval('player_advanced_stats_id_seq'::regclass),
  "team_id" uuid NOT NULL,
  "player_name" text NOT NULL,
  "is_our_team" boolean NOT NULL DEFAULT false,
  "generated_at" timestamptz NOT NULL DEFAULT now(),
  "games" integer,
  "total_pitches" integer,
  "gb" integer,
  "fb" integer,
  "ld" integer,
  "batted_balls" integer,
  "gb_pct" numeric,
  "fb_pct" numeric,
  "ld_pct" numeric,
  "spray_lf" integer,
  "spray_cf" integer,
  "spray_rf" integer,
  "spray_3b" integer,
  "spray_ss" integer,
  "spray_2b" integer,
  "spray_1b" integer,
  "spray_pc" integer,
  "spray_lf_pct" numeric,
  "spray_cf_pct" numeric,
  "spray_rf_pct" numeric,
  "spray_3b_pct" numeric,
  "spray_ss_pct" numeric,
  "spray_2b_pct" numeric,
  "spray_1b_pct" numeric,
  "spray_pc_pct" numeric,
  "risp_ab" integer,
  "risp_h" integer,
  "ba_risp" numeric,
  "swing_decisions" text,
  "k_pct" numeric,
  "bb_pct" numeric,
  "org_id" uuid,
  "errors" integer DEFAULT 0,
  "bunts" integer DEFAULT 0,
  "spray_by_count" text,
  primary key ("id")
);

create table if not exists public."players" (
  "id" uuid NOT NULL DEFAULT extensions.uuid_generate_v4(),
  "org_id" uuid NOT NULL,
  "team_id" uuid NOT NULL,
  "full_name" text NOT NULL,
  "jersey_number" text,
  "position" text,
  "bats" character,
  "throws" character,
  "gc_player_id" text,
  "is_active" boolean NOT NULL DEFAULT true,
  "created_at" timestamptz NOT NULL DEFAULT now(),
  "updated_at" timestamptz NOT NULL DEFAULT now(),
  primary key ("id")
);

create table if not exists public."profiles" (
  "id" uuid NOT NULL,
  "display_name" text,
  "avatar_url" text,
  "created_at" timestamptz NOT NULL DEFAULT now(),
  "updated_at" timestamptz NOT NULL DEFAULT now(),
  primary key ("id")
);

create table if not exists public."reports" (
  "id" uuid NOT NULL DEFAULT extensions.uuid_generate_v4(),
  "org_id" uuid NOT NULL,
  "created_by" uuid,
  "linked_team_id" uuid,
  "report_type" text NOT NULL DEFAULT 'opponent'::text,
  "format" report_format NOT NULL DEFAULT 'pdf'::report_format,
  "status" report_status NOT NULL DEFAULT 'pending'::report_status,
  "title" text NOT NULL,
  "storage_path" text,
  "public_url" text,
  "ai_model" text,
  "games_analyzed" integer,
  "error_message" text,
  "generated_at" timestamptz,
  "created_at" timestamptz NOT NULL DEFAULT now(),
  "updated_at" timestamptz NOT NULL DEFAULT now(),
  primary key ("id")
);

create table if not exists public."scouting_feedback_submissions" (
  "id" uuid NOT NULL DEFAULT gen_random_uuid(),
  "org_id" uuid,
  "team_id" uuid NOT NULL,
  "player_id" uuid,
  "game_id" uuid,
  "submitted_by" uuid,
  "submitted_by_email" text,
  "feedback_text" text NOT NULL,
  "feedback_type" text,
  "ai_plausibility_score" integer,
  "ai_verdict" text,
  "ai_supporting_evidence" jsonb,
  "ai_conflicting_evidence" jsonb,
  "review_status" text NOT NULL DEFAULT 'pending'::text,
  "reviewer_notes" text,
  "created_at" timestamptz DEFAULT now(),
  "reviewed_at" timestamptz,
  primary key ("id")
);

create table if not exists public."scouting_reports" (
  "id" bigint NOT NULL DEFAULT nextval('scouting_reports_id_seq'::regclass),
  "team_id" uuid,
  "report_type" text NOT NULL DEFAULT 'full_scout'::text,
  "games_covered" text,
  "file_path" text,
  "file_format" text NOT NULL DEFAULT 'pdf'::text,
  "recipient_email" text,
  "created_at" timestamptz NOT NULL DEFAULT now(),
  primary key ("id")
);

create table if not exists public."scrape_jobs" (
  "id" uuid NOT NULL DEFAULT extensions.uuid_generate_v4(),
  "org_id" uuid NOT NULL,
  "team_id" uuid,
  "initiated_by" uuid,
  "source" scrape_source NOT NULL,
  "source_url" text NOT NULL,
  "status" scrape_status NOT NULL DEFAULT 'pending'::scrape_status,
  "games_found" integer NOT NULL DEFAULT 0,
  "games_ingested" integer NOT NULL DEFAULT 0,
  "error_message" text,
  "log_text" text,
  "started_at" timestamptz,
  "finished_at" timestamptz,
  "created_at" timestamptz NOT NULL DEFAULT now(),
  primary key ("id")
);

create table if not exists public."stat_validation_runs" (
  "id" uuid NOT NULL DEFAULT gen_random_uuid(),
  "team_id" uuid NOT NULL,
  "created_at" timestamptz NOT NULL DEFAULT now(),
  "status" text NOT NULL DEFAULT 'complete'::text CHECK (status = ANY (ARRAY['complete'::text, 'failed'::text, 'partial'::text])),
  "games_total" integer NOT NULL DEFAULT 0,
  "games_with_box_score" integer NOT NULL DEFAULT 0,
  "games_with_play_by_play" integer NOT NULL DEFAULT 0,
  "games_validated" integer NOT NULL DEFAULT 0,
  "games_mismatched" integer NOT NULL DEFAULT 0,
  "official_batting" jsonb NOT NULL DEFAULT '{}'::jsonb,
  "official_pitching" jsonb NOT NULL DEFAULT '{}'::jsonb,
  "reconstructed_batting" jsonb NOT NULL DEFAULT '{}'::jsonb,
  "reconstructed_pitching_defense" jsonb NOT NULL DEFAULT '{}'::jsonb,
  "deltas" jsonb NOT NULL DEFAULT '{}'::jsonb,
  "side_specific_tendencies" jsonb NOT NULL DEFAULT '{}'::jsonb,
  "warnings" jsonb NOT NULL DEFAULT '[]'::jsonb,
  "confidence" text NOT NULL DEFAULT 'low'::text CHECK (confidence = ANY (ARRAY['low'::text, 'medium'::text, 'high'::text])),
  primary key ("id")
);

create table if not exists public."stripe_webhook_events" (
  "id" text NOT NULL,
  "type" text NOT NULL,
  "processed_at" timestamptz NOT NULL DEFAULT now(),
  primary key ("id")
);

create table if not exists public."teams" (
  "id" uuid NOT NULL DEFAULT extensions.uuid_generate_v4(),
  "org_id" uuid NOT NULL,
  "team_name" text NOT NULL,
  "age_group" text,
  "is_our_team" boolean NOT NULL DEFAULT false,
  "gc_team_url" text,
  "pg_team_url" text,
  "notes" text,
  "created_at" timestamptz NOT NULL DEFAULT now(),
  "updated_at" timestamptz NOT NULL DEFAULT now(),
  "city" text,
  "state" text,
  "classification" text,
  "raw_team_name" text,
  "gc_search_name" text,
  "season_year" text,
  "season_type" text,
  "unattributed_errors_our_side" integer DEFAULT 0,
  "unattributed_errors_opponent_side" integer DEFAULT 0,
  "archived" boolean NOT NULL DEFAULT false,
  primary key ("id")
);

-- ── Unique constraints ──────────────────────────────────────────────────
alter table public."organizations" add constraint "organizations_slug_key" unique ("slug");
alter table public."organizations" add constraint "organizations_stripe_customer_id_key" unique ("stripe_customer_id");
alter table public."organizations" add constraint "organizations_stripe_subscription_id_key" unique ("stripe_subscription_id");
alter table public."at_bats" add constraint "at_bats_game_id_gc_ab_id_key" unique ("game_id", "gc_ab_id");
alter table public."batting_lines" add constraint "batting_lines_game_player_side_key" unique ("game_id", "player_name", "is_our_team");
alter table public."games" add constraint "games_org_id_gc_game_id_key" unique ("org_id", "gc_game_id");
alter table public."org_members" add constraint "org_members_org_id_user_id_key" unique ("org_id", "user_id");
alter table public."pitching_lines" add constraint "pitching_lines_game_player_side_key" unique ("game_id", "player_name", "is_our_team");
alter table public."play_events" add constraint "play_events_game_sequence_key" unique ("game_id", "sequence_num");
alter table public."player_advanced_stats" add constraint "player_advanced_stats_team_id_player_name_is_our_team_key" unique ("team_id", "player_name", "is_our_team");
alter table public."pitcher_advanced_stats" add constraint "pitcher_advanced_stats_team_id_player_name_is_our_team_key" unique ("team_id", "player_name", "is_our_team");
alter table public."players" add constraint "players_team_id_gc_player_id_key" unique ("team_id", "gc_player_id");
alter table public."teams" add constraint "teams_org_id_team_name_age_group_key" unique ("org_id", "team_name", "age_group");

-- ── Foreign keys (verified ON DELETE rules; ON UPDATE is NO ACTION for
--    every one of these, confirmed via information_schema, so it's omitted
--    -- that's Postgres's own default, not an unstated assumption) ────────
alter table public."at_bats" add constraint "at_bats_batter_id_fkey" foreign key ("batter_id") references public."players" ("id");
alter table public."at_bats" add constraint "at_bats_game_id_fkey" foreign key ("game_id") references public."games" ("id") on delete cascade;
alter table public."at_bats" add constraint "at_bats_org_id_fkey" foreign key ("org_id") references public."organizations" ("id") on delete cascade;
alter table public."at_bats" add constraint "at_bats_pitcher_id_fkey" foreign key ("pitcher_id") references public."players" ("id");
alter table public."batting_lines" add constraint "batting_lines_game_id_fkey" foreign key ("game_id") references public."games" ("id") on delete cascade;
alter table public."batting_lines" add constraint "batting_lines_org_id_fkey" foreign key ("org_id") references public."organizations" ("id");
alter table public."batting_lines" add constraint "batting_lines_team_id_fkey" foreign key ("team_id") references public."teams" ("id") on delete cascade;
alter table public."derived_team_verified_totals" add constraint "derived_team_verified_totals_run_id_fkey" foreign key ("run_id") references public."stat_validation_runs" ("id") on delete set null;
alter table public."derived_team_verified_totals" add constraint "derived_team_verified_totals_team_id_fkey" foreign key ("team_id") references public."teams" ("id") on delete cascade;
alter table public."game_stat_validation_results" add constraint "game_stat_validation_results_game_id_fkey" foreign key ("game_id") references public."games" ("id") on delete cascade;
alter table public."game_stat_validation_results" add constraint "game_stat_validation_results_run_id_fkey" foreign key ("run_id") references public."stat_validation_runs" ("id") on delete cascade;
alter table public."game_stat_validation_results" add constraint "game_stat_validation_results_team_id_fkey" foreign key ("team_id") references public."teams" ("id") on delete cascade;
alter table public."games" add constraint "games_opponent_id_fkey" foreign key ("opponent_id") references public."teams" ("id");
alter table public."games" add constraint "games_org_id_fkey" foreign key ("org_id") references public."organizations" ("id") on delete cascade;
alter table public."games" add constraint "games_our_team_id_fkey" foreign key ("our_team_id") references public."teams" ("id");
alter table public."games" add constraint "games_team_id_fkey" foreign key ("team_id") references public."teams" ("id");
alter table public."org_members" add constraint "org_members_invited_by_fkey" foreign key ("invited_by") references public."profiles" ("id");
alter table public."org_members" add constraint "org_members_org_id_fkey" foreign key ("org_id") references public."organizations" ("id") on delete cascade;
alter table public."org_members" add constraint "org_members_user_id_fkey" foreign key ("user_id") references public."profiles" ("id") on delete cascade;
alter table public."pitcher_advanced_stats" add constraint "pitcher_advanced_stats_org_id_fkey" foreign key ("org_id") references public."organizations" ("id");
alter table public."pitcher_advanced_stats" add constraint "pitcher_advanced_stats_team_id_fkey" foreign key ("team_id") references public."teams" ("id") on delete cascade;
alter table public."pitches" add constraint "pitches_at_bat_id_fkey" foreign key ("at_bat_id") references public."at_bats" ("id") on delete cascade;
alter table public."pitches" add constraint "pitches_game_id_fkey" foreign key ("game_id") references public."games" ("id") on delete cascade;
alter table public."pitches" add constraint "pitches_org_id_fkey" foreign key ("org_id") references public."organizations" ("id") on delete cascade;
alter table public."pitches" add constraint "pitches_pitcher_id_fkey" foreign key ("pitcher_id") references public."players" ("id");
alter table public."pitching_lines" add constraint "pitching_lines_game_id_fkey" foreign key ("game_id") references public."games" ("id") on delete cascade;
alter table public."pitching_lines" add constraint "pitching_lines_org_id_fkey" foreign key ("org_id") references public."organizations" ("id");
alter table public."pitching_lines" add constraint "pitching_lines_team_id_fkey" foreign key ("team_id") references public."teams" ("id") on delete cascade;
alter table public."play_events" add constraint "play_events_game_id_fkey" foreign key ("game_id") references public."games" ("id") on delete cascade;
alter table public."play_events" add constraint "play_events_org_id_fkey" foreign key ("org_id") references public."organizations" ("id");
alter table public."play_events" add constraint "play_events_team_id_fkey" foreign key ("team_id") references public."teams" ("id") on delete cascade;
alter table public."player_advanced_stats" add constraint "player_advanced_stats_org_id_fkey" foreign key ("org_id") references public."organizations" ("id");
alter table public."player_advanced_stats" add constraint "player_advanced_stats_team_id_fkey" foreign key ("team_id") references public."teams" ("id") on delete cascade;
alter table public."players" add constraint "players_org_id_fkey" foreign key ("org_id") references public."organizations" ("id") on delete cascade;
alter table public."players" add constraint "players_team_id_fkey" foreign key ("team_id") references public."teams" ("id") on delete cascade;
alter table public."reports" add constraint "reports_created_by_fkey" foreign key ("created_by") references public."profiles" ("id");
alter table public."reports" add constraint "reports_linked_team_id_fkey" foreign key ("linked_team_id") references public."teams" ("id");
alter table public."reports" add constraint "reports_org_id_fkey" foreign key ("org_id") references public."organizations" ("id") on delete cascade;
alter table public."scouting_reports" add constraint "scouting_reports_team_id_fkey" foreign key ("team_id") references public."teams" ("id");
alter table public."scrape_jobs" add constraint "scrape_jobs_initiated_by_fkey" foreign key ("initiated_by") references public."profiles" ("id");
alter table public."scrape_jobs" add constraint "scrape_jobs_org_id_fkey" foreign key ("org_id") references public."organizations" ("id") on delete cascade;
alter table public."scrape_jobs" add constraint "scrape_jobs_team_id_fkey" foreign key ("team_id") references public."teams" ("id");
alter table public."stat_validation_runs" add constraint "stat_validation_runs_team_id_fkey" foreign key ("team_id") references public."teams" ("id") on delete cascade;
alter table public."teams" add constraint "teams_org_id_fkey" foreign key ("org_id") references public."organizations" ("id") on delete cascade;
